import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["500", "600", "700"], // Choose the weights you need
  variable: "--font-poppins", // Optional: use CSS variable
});

export const metadata = {
  title: "Survey Form",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body
        className={`${poppins.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
